networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: unless-stopped
    networks:
      - frontend
      - app
    ports:
      - '8080'
    environment:
      NGINX_WEB_ROOT: /app/htdocs
      NGINX_PORT: 8080
      NGINX_MAX_BODY_SIZE: 1M
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - ./:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
#      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
